-- select T.TRAINID , T.TRAINNAME, SA.CLASSID, COUNT(SA.TRAINSEATID)
-- from SEAT_ALLOCATION SA JOIN TRAIN T ON(T.TRAINID = SA.TRAINID)
-- where SA.FROMSTATIONID = 'RAJ' AND SA.TOSTATIONID = 'ISB' AND TO_CHAR(TO_DATE('26-06-2025', 'DD-MM-YYYY'),'Dy') <> T.OFFDAY
-- GROUP BY T.TRAINID , T.TRAINNAME, SA.CLASSID;


-- AVAILABLE SEATCOUNT
-- select count(TICKET.TICKETID) AS AVAILABLE
-- from TICKET
-- where 
--     TRAVELDATE = TO_DATE('26-06-2025', 'DD-MM-YYYY') and
--     TicketStatus = 'AVAILABLE' AND 
--     TRAINSEATID in
--     (select SA.TRAINSEATID
--     from SEAT_ALLOCATION SA JOIN TRAIN T ON(T.TRAINID = SA.TRAINID)
--     where SA.FROMSTATIONID = 'RAJ' AND SA.TOSTATIONID = 'ISB' AND TO_CHAR(TICKET.TRAVELDATE,'Dy') <> T.OFFDAY
--     GROUP BY T.TRAINID , T.TRAINNAME, SA.CLASSID, SA.TRAINSEATID);

-- --TIME 1
-- SELECT TO_CHAR(DEPARTURETIME, 'HH:MM:SS PM') FROM ROUTE 
-- WHERE FROMSTATIONID = 'ISB' AND
--         TRAINID = 'T760';

-- SELECT TO_CHAR(ARRIVALTIME, 'HH:MM:SS PM') FROM ROUTE 
-- WHERE FROMSTATIONID = 'DHK' AND
--         TRAINID = 'T760';

------CLASSWISE WITH FARE
select C.CLASSNAME, SA.FARE, count(TICKET.TICKETID) AS AVAILABLECOUNT
from TICKET JOIN SEAT_ALLOCATION SA 
ON(SA.FROMSTATIONID = 'RAJ' AND SA.TOSTATIONID = 'ISB' AND TICKET.TrainSeatId = SA.TRAINSEATID)
JOIN TRAIN T ON(T.TRAINID = 'T760' AND T.TRAINID = SA.TRAINID AND TO_CHAR(TICKET.TRAVELDATE,'Dy') <> T.OFFDAY) JOIN CLASS C ON(C.CLASSID = SA.CLASSID)
where 
    TRAVELDATE = TO_DATE('26-06-2025', 'DD-MM-YYYY') and
    TicketStatus = 'AVAILABLE' 
GROUP BY SA.CLASSID, C.CLASSNAME, SA.FARE;
    
--STATIC

select T.TRAINID , T.TRAINNAME ,
(SELECT TO_CHAR(DEPARTURETIME, 'HH:MM:SS PM') FROM ROUTE R1
WHERE R1.FROMSTATIONID = 'RAJ' AND
        R1.TRAINID = T.TRAINID
) AS DEPARTURE_TIME,
(SELECT TO_CHAR(ARRIVALTIME, 'HH:MM:SS PM') FROM ROUTE R2
    WHERE R2.FROMSTATIONID = 'ISB' AND
        R2.TRAINID = T.TRAINID
) AS ARRIVALTIME
from SEAT_ALLOCATION SA JOIN TRAIN T ON(T.TRAINID = SA.TRAINID)
where SA.FROMSTATIONID = 'RAJ' AND SA.TOSTATIONID = 'ISB' AND TO_CHAR(TO_DATE('25-06-2025', 'DD-MM-YYYY'),'Dy') <> T.OFFDAY
GROUP BY T.TRAINID , T.TRAINNAME;



--combined 

select T.TRAINID, T.TRAINNAME,
(SELECT TO_CHAR(DEPARTURETIME, 'HH:MI:SS AM') 
FROM ROUTE R1 
WHERE R1.FROMSTATIONID = 'RAJ' AND R1.TRAINID = T.TRAINID) AS DEPARTURE_TIME,
(SELECT TO_CHAR(ARRIVALTIME, 'HH:MI:SS AM') 
FROM ROUTE R2 
WHERE R2.FROMSTATIONID = 'DHK' AND R2.TRAINID = T.TRAINID) AS ARRIVAL_TIME,
C.CLASSNAME, SA.FARE, COUNT(TICKET.TICKETID) AS AVAILABLECOUNT
FROM TICKET
JOIN SEAT_ALLOCATION SA 
    ON SA.TRAINSEATID = TICKET.TRAINSEATID
    AND SA.FROMSTATIONID = 'RAJ'
    AND SA.TOSTATIONID = 'DHK'
JOIN TRAIN T 
    ON T.TRAINID = SA.TRAINID 
    AND TO_CHAR(TICKET.TRAVELDATE, 'Dy') <> T.OFFDAY
JOIN CLASS C 
    ON C.CLASSID = SA.CLASSID
WHERE TICKET.TRAVELDATE = TO_DATE('26-06-2025', 'DD-MM-YYYY')
    AND TICKET.TicketStatus = 'AVAILABLE'
GROUP BY T.trainId, T.trainName, SA.CLASSID, C.CLASSNAME, SA.FARE;
    