INSERT INTO AVAILABLE_DATES (TravelDate) VALUES (TO_DATE('20-06-2025', 'DD-MM-YYYY'));
INSERT INTO AVAILABLE_DATES (TravelDate) VALUES (TO_DATE('21-06-2025', 'DD-MM-YYYY'));
INSERT INTO AVAILABLE_DATES (TravelDate) VALUES (TO_DATE('22-06-2025', 'DD-MM-YYYY'));
INSERT INTO AVAILABLE_DATES (TravelDate) VALUES (TO_DATE('23-06-2025', 'DD-MM-YYYY'));
INSERT INTO AVAILABLE_DATES (TravelDate) VALUES (TO_DATE('24-06-2025', 'DD-MM-YYYY'));
INSERT INTO AVAILABLE_DATES (TravelDate) VALUES (TO_DATE('25-06-2025', 'DD-MM-YYYY'));
INSERT INTO AVAILABLE_DATES (TravelDate) VALUES (TO_DATE('26-06-2025', 'DD-MM-YYYY'));
