ALTER TABLE USER_INFO DROP UNIQUE (Email);
ALTER TABLE USER_INFO DROP UNIQUE (PhoneNum);
ALTER TABLE USER_INFO DROP UNIQUE (NID);
ALTER TABLE USER_INFO DROP UNIQUE (Birth_Reg_Num);

ALTER TABLE USER_INFO
ADD CONSTRAINT USER_INFO_EMAIL_UK UNIQUE (Email);

ALTER TABLE USER_INFO
ADD CONSTRAINT USER_INFO_PHONE_UK UNIQUE (PhoneNum);

ALTER TABLE USER_INFO
ADD CONSTRAINT USER_INFO_NID_UK UNIQUE (NID);

ALTER TABLE USER_INFO
ADD CONSTRAINT USER_INFO_BIRTHREG_UK UNIQUE (Birth_Reg_Num);


--24 july

ALTER TABLE USER_INFO
ADD BannedUntil TIMESTAMP;
