spring.application.name=railway

# JDBC URL EXAMPLE = jdbc:oracle:thin:@<YOUR_DATABASE_HOST>:<YOUR_DATABASE_PORT>/<YOUR_DATABASE_NAME>
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB1
spring.datasource.username=SYS as sysdba
spring.datasource.password=1234

# Properties for UCP - Universal Connection Pool (UCP). Spring Boot 2.4.0 or above is required
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=1
spring.datasource.oracleucp.min-pool-size=1
spring.datasource.oracleucp.max-pool-size=2
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource

#sslCommerz

sslcommerz.store_id=recom66a5acd9bd134
sslcommerz.store_passwd=recom66a5acd9bd134@ssl
sslcommerz.is_live=false

frontend.base-url=http://localhost:3000
backend.base-url=http://localhost:8080


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG
