CREATE OR REPLACE PROCEDURE Release_REFUNDED_Tickets_By_BookingId(I_BookingId in VARCHAR2) IS
BEGIN
    UPDATE TICKET
    SET TICKETSTATUS = 'AVAILABLE'
    WHERE TICKETSTATUS = 'BOOKED'
    AND BOOKINGID = I_BookingId;
    COMMIT;
END;
/